version: '3.3'

services:
    wordpress:
        image: wordpress
        #build: Wordpress/
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_PASSWORD: example

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: example
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3306"]
            interval: 30s
            timeout: 10s
            retries: 5
